name: default
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
"on":
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release-*


env:
  PLATFORM: linux/arm64
  INSTALLER_ARCH: targetarch
  USERNAME: buyuliang
  TALOS_VERSION: v1.7.4
  REALKTEK_FIRMWARE_EXTENSION_IMAGE: ghcr.io/siderolabs/realtek-firmware:20240513@sha256:4ca40c2836c1cdb5105456186afd880925d72e81ee6b0ff69a40c9c05b7b74a4

jobs:

  boards:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        kernel:
          - bsp
        board:
          - name: rock-5b
            chipset: rk3588
    env:
      SBC_RK3588_TAG: ${{ needs.sbc-rk3588.outputs.SBC_RK3588_TAG }}
    steps:
      - name: Build installer image
        if: github.event_name != 'pull_request'
        run: |
          docker run --rm -t -v ./_out:/out -v /dev:/dev --privileged ghcr.io/${{ env.USERNAME }}/imager:${{ env.SBC_RK3588_TAG }}-${{ matrix.kernel }} \
            installer --arch arm64 \
              --base-installer-image="ghcr.io/siderolabs/installer:${{ env.TALOS_VERSION }}" \
              --overlay-name=rk3588 \
              --overlay-image=ghcr.io/${{ env.USERNAME }}/talos-sbc-rk3588:${{ env.SBC_RK3588_TAG }} \
              --overlay-option="board=${{ matrix.board.name }}" \
              --overlay-option="chipset=${{ matrix.board.chipset }}" \
              --system-extension-image="${{ env.REALKTEK_FIRMWARE_EXTENSION_IMAGE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SBC_RK3588_TAG: v1.0-2-g887279e

      - name: Push installer image
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | crane auth login ghcr.io --username "${{ env.USERNAME }}" --password-stdin
          crane push _out/installer-arm64.tar ghcr.io/${{ env.USERNAME }}/talos-rk3588:${{ env.SBC_RK3588_TAG }}-${{ matrix.board.name }}-${{ matrix.kernel }}

      - name: Build flashable image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker run --rm -t -v ./_out:/out -v /dev:/dev --privileged ghcr.io/${{ env.USERNAME }}/imager:${{ env.SBC_RK3588_TAG }}-${{ matrix.kernel }} \
          metal --arch arm64 \
            --overlay-image=ghcr.io/${{ env.USERNAME }}/talos-sbc-rk3588-${{ matrix.kernel }}:${{ env.SBC_RK3588_TAG }} \
            --overlay-name=rk3588 \
            --overlay-option="board=${{ matrix.board.name }}" \
            --overlay-option="chipset=${{ matrix.board.chipset }}" \
            --base-installer-image="ghcr.io/${{ env.USERNAME }}/talos-rk3588:${{ env.SBC_RK3588_TAG }}-${{ matrix.board.name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare flashable image for upload
        run: |
          docker run --rm -t -v ./_out:/out alpine mv /out/metal-arm64.raw.xz /out/talos-${{ env.SBC_RK3588_TAG }}-${{ matrix.board.name }}-${{ matrix.kernel }}.raw.xz

      - uses: actions/upload-artifact@v4
        with:
          name: talos-metal-${{ matrix.board.chipset }}-${{ matrix.board.name }}-${{ env.SBC_RK3588_TAG }}-${{ matrix.kernel }}
          path: _out/talos-*.raw.xz
          compression-level: 0 # already compressed
          if-no-files-found: error

      - name: Cleanup
        if: always()
        continue-on-error: true
        run: |
          crane auth logout ghcr.io
          # HACK: files are owned by root, (ab)use Docker as sudo
          docker run --rm -t -v ./_out:/out alpine sh -c 'rm -rf /out/*'

  release:
    runs-on: ubuntu-latest
    needs: [boards]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Release
        uses: crazy-max/ghaction-github-release@v2
        with:
          files: |
            talos-*.raw.xz
